# Generated by Django 2.2 on 2022-04-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview_app', '0002_auto_20220401_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image1',
            field=models.ImageField(upload_to='review_pics'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image2',
            field=models.ImageField(blank=True, upload_to='review_pics'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image3',
            field=models.ImageField(blank=True, upload_to='review_pics'),
        ),
    ]
